language: cpp
compiler:
  - clang
  - gcc
# branches:
#  only:
#    - master
script:
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j2
  - ctest
notifications:
  email: false

# container-based builds
sudo: false
