rwxr-xr-x USER_NAME USER_ID GROUP_NAME GROUP_ID alpha
rw-r--r-- USER_NAME USER_ID GROUP_NAME GROUP_ID beta
rw-r----- USER_NAME USER_ID GROUP_NAME GROUP_ID gamma
rw------- USER_NAME USER_ID GROUP_NAME GROUP_ID delta
rwxrwxrwx USER_NAME USER_ID GROUP_NAME GROUP_ID sub
--x-w-r-- USER_NAME USER_ID GROUP_NAME GROUP_ID sub/epsilon
rw-r-xr-- USER_NAME USER_ID GROUP_NAME GROUP_ID sub/riemann
r---wx-w- USER_NAME USER_ID GROUP_NAME GROUP_ID sub/zeta
